
LOCAL_PATH:= $(call my-dir)
LOCAL_C_INCLUDES := $(LOCAL_PATH)

include $(CLEAR_VARS)

LOCAL_MODULE    := libSW
LOCAL_C_INCLUDES += $(GLOBAL_C_INCLUDES)
LOCAL_SRC_FILES := _SW.c

LOCAL_CFLAGS := $(GLOBAL_CFLAGS)

include $(BUILD_STATIC_LIBRARY)
